### ISSUE TITLE
Action with parameter?

### ISSUE THREAD

**Issue by mjsarfatti** [ibloat/riot-redux-mixin#1]
Hello,
how do I dispatch an action with a parameter?

My action:

``` javascript
function updateStar(points) { // action creator
    return {
        type: TREE_STAR_CHANGE,
        payload: points
    };
}
```

My reducer:

``` javascript
function tree(state = {}, action) {
    console.log(action);
}
```

In the tag:

``` javascript
this.dispatchify({ updateStar });
this.updateStar(3);
```

In the console:

`Object {type: "TREE_STAR_CHANGE", payload: undefined}`

In your example you only use actions with no parameters (increment, decrement), and I couldn't find anything else around about this specific case. I'm wondering if your mixin even allows that? Thank you for any help.

EDIT: code highlighting

**Comment by mjsarfatti** [comment]
Replying to myself: with this mixin you can pass parameters only if you dispatch the action directly, eg:

``` javascript
this.dispatch(myAction(...args));
```

Using dispatchify is equivalent to calling the action with no arguments:

``` javascript
this.dispatchify({ myAction });
this.myAction(...args);

// ignores ...args and is actually equivalent to:
this.dispatch(myAction());
```

I would suggest either clarifying this in the README, or even fixing the behavior.

Thank you for the mixin though, super useful!

**Comment by ibloat** [comment]
Hey there, that is correct.
My use case for dispatchify was very narrow and the README should have been a bit more fleshed out in general.
I will push a fix to pass through arguments to the action creator.
Thank you for the suggestion!
For static parameters you already can pass instantiated actions to dispatchify such as

```
this.dispatchify({ myAction: myAction(someparameter) });
this.myAction() // will dispatch whatever object myAction(someparameter) created
```

**Comment by gihrig** [comment]
Exactly what I was trying to figure out ;-)

Thanks for the clarification, looking forward to the new functionality.

**Comment by ibloat** [comment]
Should be working now, pushed an update to npm :+1:
